routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('',[\App\Http\Controllers\Customer\HomeController::class,'index'])->name('home');


Route::group(['prefix'=>'admin','as'=>'admin.'],function (){
    Route::middleware([])->group(function () {
        Route::get('dashboard',[\App\Http\Controllers\Admin\DashboardController::class, 'index'])->middleware(['web'])->name('dashboard');


        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
        Route::get('categories/destroy/{id}', [\App\Http\Controllers\Admin\CategoryController::class,'destroy'])->name('categoriesDestroy');

        Route::resource('item', \App\Http\Controllers\Admin\ItemController::class);
        Route::get('item/destroy/{id}', [\App\Http\Controllers\Admin\ItemController::class,'destroy'])->name('itemDestroy');
        Route::post('item/img/{id}',[\App\Http\Controllers\Admin\ItemController::class,'storeImg'])->name('storeImg');
    });
}


);


Route::group(['prefix'=>'customer','as'=>'customer.'],function (){

    Route::group(['as'=>'auth.','middleware'=>['view']],function (){
        Route::get('login',[\App\Http\Controllers\Customer\Auth\AuthController::class,'getLogin'])->name('login');
        Route::post('postLogin',[\App\Http\Controllers\Customer\Auth\AuthController::class,'postLogin'])->name('postLogin');
        Route::get('regis',[\App\Http\Controllers\Customer\Auth\AuthController::class,'getRegis'])->name('regis');
        Route::post('postRegis',[\App\Http\Controllers\Customer\Auth\AuthController::class,'postRegis'])->name('postRegis');
    });

    Route::get('logout',[\App\Http\Controllers\Customer\Auth\AuthController::class,'logout'])->name('logout');


    Route::group(['prefix'=>'dashboard','as'=>'dashboard.','middleware'=>['customer']],function (){
        Route::get('/',[\App\Http\Controllers\Customer\Dashboard\DashboardController::class,'index'])->name('index');
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function item(){
        return $this->hasMany(Item::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index(Request $request)
    {
        if($request->ajax())
        {
            $data = Category::all();
            $b = 1;
//            $data = Mahasiswa::latest()->get();
            return DataTables::of($data)
                ->addColumn('action', function($data){
                    $button = '<a href="categories/'.$data->id.'/edit'.'" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>';
                    $button .= '<a  href="'.route('admin.categoriesDestroy',$data->id).'" class="btn btn-danger" onclick="return confirm('.'`Are you sure?`'.')"><i class="fa fa-trash"></i> Delete</a>';
                    return $button;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('admin.content.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.content.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Category();

        $validates = [
            'name' => 'required',
            'dsc' => 'required'
        ];
        $request->validate($validates);

        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->dsc = $request->dsc;
        $data->save();

//        Category::create($request->all());
        return redirect()->route('admin.categories.index')->with('success','success add item');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Category::findOrFail($id);
        view()->share([
            'data' => $data,
        ]);
        return view('admin.content.categories.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Category::findOrFail($id);
        $validates = [
            'name' => 'required',
            'dsc' => 'required'
        ];
        $request->validate($validates);
        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->dsc = $request->dsc;
        $data->save();

//        Category::create($request->all());
        return redirect()->route('admin.categories.index')->with('success','Edit Item Success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Category::findOrFail($id);
        $data->delete();

        return redirect()->route('admin.categories.index')->with('danger','delete item success ');

    }
}

resources/views/admin/content/categories/create.blade.php
@extends('admin.layout')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Product</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Modules</a></div>
                    <div class="breadcrumb-item">DataTables</div>
                </div>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="container">
                                <div class="d-flex justify-content-between pt-5">
                                    <div>
                                        <h4>Category Item</h4>

                                    </div>
                                </div>
                            </div>


                                <div class="card-body">
                                    <form action="{{route('admin.categories.store')}}" method="post">
                                        @csrf
                                        <div class="form-group row mb-4">
                                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                                            <div class="col-sm-12 col-md-7">
                                                <input type="text" name="name" id="name" class="form-control" value="{{ old('name') }}">
                                                @error('name')
                                                <div class="alert alert-danger">{{ $message }}</div>
                                                @enderror
                                            </div>

                                        </div>

                                        <div class="form-group row mb-4">
                                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Description</label>
                                            <div class="col-sm-12 col-md-7">
                                                <input type="text" name="dsc" id="dsc" class="form-control" value="{{ old('dsc') }}">
                                                @error('dsc')
                                                    <div class="alert alert-danger">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="form-group row mb-4">
                                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                            <div class="col-sm-12 col-md-7">
                                                <button class="btn btn-primary">Publish</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>


@endsection

resources/views/admin/content/categories/edit.blade.php
@extends('admin.layout')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Product</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Modules</a></div>
                    <div class="breadcrumb-item">DataTables</div>
                </div>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="container">
                                <div class="d-flex justify-content-between pt-5">
                                    <div>
                                        <h4>Category Item</h4>

                                    </div>
                                </div>
                            </div>

                                <div class="card-body">
                                    <form action="{{route('admin.categories.update',$data->id)}}" method="post">
                                        @csrf
                                        {{ method_field('PUT') }}
                                        <div class="form-group row mb-4">
                                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                                            <div class="col-sm-12 col-md-7">
                                                <input type="text" name="name" id="name" class="form-control" value="{{ $data->name }}">
                                                @error('name')
                                                <div class="alert alert-danger">{{ $message }}</div>
                                                @enderror
                                            </div>

                                        </div>

                                        <div class="form-group row mb-4">
                                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Description</label>
                                            <div class="col-sm-12 col-md-7">
                                                <input type="text" name="dsc" id="dsc" class="form-control" value="{{$data->dsc}}">
                                                @error('title')
                                                <div class="alert alert-danger">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="form-group row mb-4">
                                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                            <div class="col-sm-12 col-md-7">
                                                <button class="btn btn-primary">Edit</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>


@endsection

resources/views/admin/content/categories/index.blade.php
@extends('admin.layout')

@section('content')
    @include('admin.component.data-tabel.head-datatebel')

    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Product</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Modules</a></div>
                    <div class="breadcrumb-item">DataTables</div>
                </div>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            @if (session('success'))
                                <div class="alert alert-success">
                                    <p>{{ session('success') }}</p>
                                </div>
                            @elseif(session('danger'))
                                <div class="alert alert-danger">
                                    <p>{{ session('danger') }}</p>
                                </div>
                            @endif
                          <div class="container">

                            <div class="d-flex justify-content-between pt-5">
                                <div>
                                    <h4>Category Item</h4>

                                </div>
                                <div>
                                    <a href="{{route('admin.categories.create')}}" class="btn btn-success">New</a>

                                </div>
                            </div>

                          </div>
                            <br>


                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="category">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Dsc</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

        @include('admin.component.data-tabel.script-datatabel')
        <script type="text/javascript">
            $(document).ready(function(){
                $('#category').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: {
                        url: "{{ route('admin.categories.index') }}",
                    },
                    columns: [
                        {
                            data: 'name',
                            name: 'name'
                        },
                        {
                            data: 'dsc',
                            name: 'dsc'
                        },
                        {
                            data: 'action',
                            name: 'action',
                            orderable: false
                        },

                    ]
                });
            });
        </script>
@endsection